name: Setup FluentCI
description: Download, install, and setup FluentCI CLI to your path.
author: Tsiry Sandratraina
branding:
  icon: play-circle
  color: purple
inputs:
  dagger-version:
    description: Dagger version to install
    required: false
    default: 0.9.10
outputs:
  version:
    description: FluentCI CLI version installed
runs:
  using: node16
  main: dist/action.js